/* Automatically generated, don't edit */
/* Generated on: tyson-Lenovo-ideapad-120S-14IAP */
/* At: Sat, 25 Jan 2020 19:07:37 +0000 */
/* Linux version 5.0.0-38-generic (buildd@lgw01-amd64-036) (gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)) #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 */

/* Pistachio Kernel Configuration System */

/* Hardware */

/* Basic Architecture */
#undef  CONFIG_ARCH_X86
#undef  CONFIG_ARCH_POWERPC
#define CONFIG_ARCH_POWERPC64 1


/* X86 Processor Architecture */
#undef  CONFIG_SUBARCH_X32
#undef  CONFIG_SUBARCH_X64


/* Processor Type */
#undef  CONFIG_CPU_X86_I486
#undef  CONFIG_CPU_X86_I586
#undef  CONFIG_CPU_X86_I686
#undef  CONFIG_CPU_X86_P4
#undef  CONFIG_CPU_X86_K8
#undef  CONFIG_CPU_X86_C3
#undef  CONFIG_CPU_X86_SIMICS


/* Platform */
#undef  CONFIG_PLAT_PC99
#undef  CONFIG_PLAT_EFI


/* Processor Type */
#undef  CONFIG_CPU_POWERPC_PPC440
#undef  CONFIG_CPU_POWERPC_IBM750
#undef  CONFIG_CPU_POWERPC_PPC604


/* Platform */
#undef  CONFIG_PLAT_OFPPC
#undef  CONFIG_PLAT_PPC44X


/* Sub-Platform */
#undef  CONFIG_SUBPLAT_440_BGP
#undef  CONFIG_SUBPLAT_440_EBONY


/* Platform */
#define CONFIG_PLAT_OFG5 1
#undef  CONFIG_PLAT_OFPOWER3
#undef  CONFIG_PLAT_OFPOWER4


/* Processor Type */
#undef  CONFIG_CPU_POWERPC64_POWER3
#undef  CONFIG_CPU_POWERPC64_POWER3p
#undef  CONFIG_CPU_POWERPC64_POWER4
#undef  CONFIG_CPU_POWERPC64_POWER4p
#define CONFIG_CPU_POWERPC64_PPC970 1


/* Miscellaneous */
#define CONFIG_IOAPIC 1
#define CONFIG_MAX_IOAPICS 2
#define CONFIG_APIC_TIMER_TICK 1000
#define CONFIG_PPC_EXPOSE_OPIC 1
#define CONFIG_BOOTMEM_PAGES 1024

#undef  CONFIG_SMP


/* Kernel */
#undef  CONFIG_EXPERIMENTAL
#undef  CONFIG_IPC_FASTPATH
#define CONFIG_DEBUG 1
#undef  CONFIG_DEBUG_SYMBOLS
#undef  CONFIG_PERFMON
#undef  CONFIG_SPIN_WHEELS
#undef  CONFIG_NEW_MDB
#undef  CONFIG_STATIC_TCBS
#define CONFIG_PPC_BAT_SYSCALLS 1
#undef  CONFIG_PPC64_TRASH_OF
#undef  CONFIG_X86_SMALL_SPACES
#undef  CONFIG_X86_COMPATIBILITY_MODE


/* Debugger */

/* Kernel Debugger Console */
#define CONFIG_KDB_CONS_COM 1
#define CONFIG_KDB_COMPORT 0x0
#define CONFIG_KDB_COMSPEED 115200
#undef  CONFIG_KDB_CONS_KBD
#undef  CONFIG_KDB_CONS_OF1275
#undef  CONFIG_KDB_CONS_PSIM_COM
#undef  CONFIG_KDB_CONS_RTAS
#define CONFIG_KDB_BOOT_CONS 0

#undef  CONFIG_KDB_DISAS
#undef  CONFIG_KDB_ON_STARTUP
#undef  CONFIG_KDB_BREAKIN
#undef  CONFIG_KDB_BREAKIN_BREAK
#undef  CONFIG_KDB_INPUT_HLT
#undef  CONFIG_KDB_NO_ASSERTS

/* Trace Settings */
#undef  CONFIG_VERBOSE_INIT
#undef  CONFIG_TRACEPOINTS
#undef  CONFIG_KMEM_TRACE
#undef  CONFIG_TRACEBUFFER



/* Code Generator Options */
#define CONFIG_SYSV_ABI 1
#undef  CONFIG_PPC_SEGMENT_LOOP
#define CONFIG_PPC_MULTIWORD_INSTR 1


/* Derived symbols */
#define CONFIG_HAVE_MEMORY_CONTROL 1
#undef  CONFIG_X86_PSE
#define CONFIG_BIGENDIAN 1
#undef  CONFIG_PPC_MMU_TLB
#undef  CONFIG_X86_SYSENTER
#undef  CONFIG_X86_PGE
#undef  CONFIG_X86_FXSR
#undef  CONFIG_IS_32BIT
#undef  CONFIG_X86_HTT
#undef  CONFIG_X86_PAT
#undef  CONFIG_PPC_BOOKE
#define CONFIG_IS_64BIT 1
#undef  CONFIG_MULTI_ARCHITECTURE
#undef  CONFIG_X86_EM64T
#undef  CONFIG_PPC_CACHE_L1_WRITETHROUGH
#undef  CONFIG_PPC_TLB_INV_LOCAL
#undef  CONFIG_PPC_CACHE_ICBI_LOCAL
#undef  CONFIG_X86_SMALL_SPACES_GLOBAL
#undef  CONFIG_X86_HVM
#undef  CONFIG_PPC_MMU_SEGMENTS
#undef  CONFIG_X86_TSC
/* That's all, folks! */
#define AUTOCONF_INCLUDED
